<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $fillable = [
        'user_id',
        'is_avatar',
        'photo_origin',
        'photo_large',
        'photo_medium',
        'photo_small'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function($photo){

        });
    }

    public function comments()
    {
        return $this->morphMany(Comment::class, 'object');
    }

    public function likes()
    {
        return $this->morphMany(Like::class, 'object');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}
